name: Build and Deploy Application
on: [push]
jobs: 
  Test-Workflow:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Welcome to workflows"
      - run: echo "Event that triggered this workflow was ${{ github.event_name }}"